## Limpieza de datos, archivo: Orders

In [2]:
# 01_orders.ipynb
import sys, os
PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))  # sube dos niveles
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import pandas as pd
from src.olistprep.data_cleaning import remove_duplicates, fill_missing_values

# Cargar el DataFrame
orders_df = pd.read_csv('../../data/raw/olist_orders_dataset.csv')

# Mostrar las primeras filas para ver los datos originales
print("Primeras filas antes de la limpieza:")
display(orders_df.head())

# Eliminar duplicados (por order_id) basados en la fecha de compra (order_purchase_timestamp)
orders_df_clean = remove_duplicates(orders_df, 'order_purchase_timestamp')

# Rellenar valores nulos
orders_df_clean = fill_missing_values(orders_df_clean)

# Verificar la limpieza:
# Verificar duplicados
duplicates_after = orders_df_clean.duplicated().sum()

# Verificar valores nulos después de la imputación
nulls_after = orders_df_clean.isnull().sum()

# Mostrar las primeras filas después de la limpieza
print("\nPrimeras filas después de la limpieza:")
display(orders_df_clean.head())

# Mostrar resultados de las verificaciones
print(f"\nNúmero de registros duplicados después de la limpieza: {duplicates_after}")
print(f"Número de valores nulos después de la limpieza:\n{nulls_after}")

# Guardar el DataFrame limpio
#orders_df_clean.to_csv('data/processed/olist_orders_clean.csv', index=False)

Primeras filas antes de la limpieza:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

Primeras filas después de la limpieza:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
60938,10a045cdf6a5650c21e9cfeb60384c16,a4b417188addbc05b26b72d5e44837a1,canceled,2018-10-17 17:30:18,Unknown,Unknown,Unknown,2018-10-30 00:00:00
68373,b059ee4de278302d550a3035c4cdb740,856336203359aa6a61bf3826f7d84c49,canceled,2018-10-16 20:16:02,Unknown,Unknown,Unknown,2018-11-12 00:00:00
31891,a2ac6dad85cf8af5b0afb510a240fe8c,4c2ec60c29d10c34bd49cb88aa85cfc4,canceled,2018-10-03 18:55:29,Unknown,Unknown,Unknown,2018-10-16 00:00:00
88500,616fa7d4871b87832197b2a137a115d2,bf6181a85bbb4115736c0a8db1a53be3,canceled,2018-10-01 15:30:09,Unknown,Unknown,Unknown,2018-10-23 00:00:00
50387,392ed9afd714e3c74767d0c4d3e3f477,2823ffda607a2316375088e0d00005ec,canceled,2018-09-29 09:13:03,Unknown,Unknown,Unknown,2018-10-15 00:00:00

Número de registros duplicados después de la limpieza: 0
Número de valores nulos después de la limpieza:
order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64